[build]
  publish = "./"
  command = ""

[functions]
  directory = "netlify/functions"

# Handy proxy redirects to avoid browser CORS for Atomic APIs
[[redirects]]
  from = "/aa/*"
  to   = "https://wax.api.atomicassets.io/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

[[redirects]]
  from = "/am/*"
  to   = "https://wax.api.atomicmarket.io/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

# Also expose the function at /api/*
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
